name = llm_connect
description = Connects your Luanti server to an LLM + integrated AI-powered Lua IDE + Lua-first runtime agency system
title = LLM Connect
author = H5N3RG
license = LGPL-3.0-or-later
version = 1.2.0
