name = llm_connect
description = Connects your Luanti server to an LLM + integrated AI-powered Lua IDE
title = LLM Connect
author = H5N3RG
license = LGPL-3.0-or-later
version = 0.9.0-dev
optional_depends = worldedit, worldeditadditions
